### ISSUE TITLE
Handle the case where customized configuration exists prior container start

### ISSUE THREAD

**Issue by petr-stratoscale** [docker-library/cassandra#110]
The container's entry point currently always  overwrites the configuration file.
This does not work well in the scenario where a customized config file is stored on a mounted volume. Any customization are then lost when the container starts.

The entry point should detect and handle (like for example Mysql and Postgres) this case.

**Comment by yosifkit** [comment]
How do you propose we detect that the config is not just the default config that we need to `sed` to the proper values?

On the other hand, since we don't have the same initdb.d directory like `postgres` and `mysql` the user can just skip the provided entrypoint when they supply their own config file.

**Comment by petr-stratoscale** [comment]
We could check the data directory and skip config if it has already been initialized (cassandra-created subdirs exist).

@yosifkit How can I skip the entry point?

Thanks.

**Comment by yosifkit** [comment]
To skip the entrypoint, basically just replace the entrypoint and command with the current command: `CMD ["cassandra", "-f"]`
```console
$ docker run --entrypoint cassandra cassandra:3.11 -f
```

You'd still need to build or map in the config file.

**Comment by tianon** [comment]
Closing given that there's a workaround that's simpler (and more reliable) than trying to detect the default configuration file. :+1:
