### ISSUE TITLE
Datacenter name

### ISSUE THREAD

**Issue by measwel** [docker-library/cassandra#124]
My setup is: one host ( ubuntu VM ) with one cassandra node.
My problem is:
`NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 0.0.0.0 datacenter1>: Unavailable('Error from server: code=1000 [Unavailable exception] message="Cannot achieve consistency level ONE" info={\'required_replicas\': 1, \'alive_replicas\': 0, \'consistency\': \'ONE\'}',)})`

I suspect that this has to do with failing replication settings:
```
      defaultReplicationStrategy: {
        'class': 'NetworkTopologyStrategy',
        'DC1': 3
      },
```
I suspect the name DC1 might not be correct for the cassandra image.
I believe the name can be set in the yml file like this:
```
      environment:
          - CASSANDRA_DC=DC1
          - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
```
Update. The above configuration seems to work well in my case. It might be worthwhile to mention the default datacenter names used by the image. I missed this information which led to the replication error above.

**Comment by qedrakmar** [comment]
Without seeing the rest of the the config, I can only guess, but if you're running a single instance, you probably don't have any replication and should probably just remove the replication settings.

As for the DC variable, from the docs at [https://hub.docker.com/_/cassandra/](https://hub.docker.com/_/cassandra/) :

CASSANDRA_DC
This variable sets the datacenter name of this node. It will set the dc option of cassandra-rackdc.properties. You must set CASSANDRA_ENDPOINT_SNITCH to use the "GossipingPropertyFileSnitch" in order for Cassandra to apply cassandra-rackdc.properties, otherwise this variable will have no effect.

So, CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch will fix that particular problem. (DC1 is the name used in example documentation, so that should be fine for the DC property)

**Comment by measwel** [comment]
Yes thank you qedrakmar. That is exactly what I did and cassandra works now. But I still have a problem when I try to map a local directory to the /var/lib/cassandra directory for data persistence.

**Comment by qedrakmar** [comment]
Okay, what is the new problem that you're having?
