### ISSUE TITLE
Allow custom configuration options via env variables

### ISSUE THREAD

**Issue by lewisdiamond** [docker-library/cassandra#142]
This would make it easy to override any configuration.

For example:
```
CASSANDRA_CFG_auto_snapshot=false
```
The script that already `sed`s the config could just check for a pattern in the environment variables and apply whatever config the user needs.

Makes it easy to work with Kubernetes, docker-compose, etc.

**Comment by gzeskas** [comment]
What is the status of this issue ?
It will allow for example override default Auth method, that now it's impossible to do.

**Comment by cchet** [comment]
I agree, why not supporting all configuration parameters via env file, or at least a possibility to point to a custom configuration file location via env var  ?

**Comment by tianon** [comment]
I'm sorry, but honestly if we're going to do anything more with environment variables it would likely be in the opposite direction (which we won't do due to the backwards compatibility implications) -- modifying a YAML file via shell script is very fragile, and setting complex configuration in this way is not great.  For custom configuration, the only/best recommendation is to provide an appropriate `cassandra.yaml` file to your running instance (via a new image with `FROM` / `COPY` in a short `Dockerfile`, via [Docker Configs](https://docs.docker.com/engine/swarm/configs/), via bind mount, etc).

Closing in favor of https://github.com/docker-library/cassandra/pull/160 + https://github.com/docker-library/docs/pull/1317.
