### ISSUE TITLE
Incremental Backups

### ISSUE THREAD

**Issue by roroettg** [docker-library/cassandra#148]
Hello,

I am wondering if there is a possibility to activate incremental_backups for the container?

It would be nice to enable incremental backups through environment variables.

**Comment by wglambert** [comment]
Closing since the issue seems resolved

If you further questions try [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
