### ISSUE TITLE
documentation update on dockerhub

### ISSUE THREAD

**Issue by tvollmer** [docker-library/cassandra#179]
Please update ( or add to ) the section on the main description page of Docker Hub ( https://hub.docker.com/_/cassandra?tab=description#connect-to-cassandra-from-cqlsh ).  The example illustrates using a "--network some-network" ... which isn't clear *why* it's needed in a single-instance mode.   Please either 

1. provide a short sentence or two about why the --network arg would be needed ( is it only for multicast in cluster mode? does it make it more secure? ), or 
2. maybe provide an example in the #connect-to-cassandra-from-cqlsh section that uses container-linking (ex in non-cluster: docker run -it --rm --link=some-cassandra:some-cassandra cassandra:3.11 cqlsh some-cassandra )

I'm new to running Cassandra in a docker container, and had to fiddle with the examples just to get started as a simple POC.  I'm assuming that option #2 is a bad idea, but I'm running on a home network, and didn't understand the need for the --network arg.

**Comment by wglambert** [comment]
Yes well, perhaps somewhat fortunately the documentation has yielded the expected results
https://github.com/docker-library/docs/pull/1441
>Ditch a lot of "--link" examples (using "--network some-network" instead to force users to do more homework)

The "homework" in reference here was meant for `docker network create`, and not necessarily why you would *want* one

**Comment by tianon** [comment]
I think the point we're trying to capture there is that Cassandra is really only useful if you can actually connect to it from some client (either interactively or via an application).  The two options for doing so within Docker are primarily sharing a Docker network or mapping ports to the host.  For the examples on that page, we illustrate that via a bogus `--network` flag because that's the more secure option and because we don't feel it's really appropriate for us to go into great lengths about the details of Docker syntax and usage in the image description. :sweat_smile:

Hopefully that helps. :+1:
