### ISSUE TITLE
Could numactl tool be added to the Dockerfile?

### ISSUE THREAD

**Issue by kangshan0910** [docker-library/cassandra#185]
Hi,
There is no numactl tool in the current image, can it be added? We need it when we want to start  multiple instances, as on the server side, running Cassandra with CPU affinity gives better performance when running multiple instances.  With numactl each instance can be pinned to distinct CPU.

**Comment by yosifkit** [comment]
Have you tried `cpuset`?

> https://stackoverflow.com/questions/42783744/docker-compose-shared-cpus

**Comment by tianon** [comment]
I think https://github.com/apache/cassandra/blob/18bcda2d4c2eba7370a0b21f33eed37cb730bbb3/bin/cassandra#L90-L100 is a pretty strong justification for adding `numactl` to the image. :sweat_smile:

(and has been in since like Cassandra 1.0: https://github.com/apache/cassandra/commit/604c0e87dc67fa65f6904ef9a98a029c9f2f865a; https://issues.apache.org/jira/browse/CASSANDRA-2594)
