### ISSUE TITLE
Can't validate the external connectivity to cassandra container via TablePlus and DevCenter

### ISSUE THREAD

**Issue by sunidhi27** [docker-library/cassandra#190]
I want to validate if we can establish external connection to the cassandra database by query Integrated development environment like TablePlus or DevCenter. 
I am passing the host-Ip of container and Port as 9042.  But its not getting connected to such applications, with an error :
No hosts available for the control connection

FYI, I am also connected to the VPN to which the host is connected to. 
I also tried by passing the Node-IP instead of host-ip, but that doesnt work.

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

**Comment by wglambert** [comment]
You should [publish](https://docs.docker.com/config/containers/container-networking/#published-ports) the port and connect to the Docker host's IP address and port, which will forward to the container.

Going to close since this doesn't seem to be an issue with the image itself but with how to use and configure it

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
