### ISSUE TITLE
mbind: Operation not permitted

### ISSUE THREAD

**Issue by AceHack** [docker-library/cassandra#203]
Logs are cluttered with "mbind: Operation not permitted".  Please resolve this issue, it's flooding the logs.  Thanks.

**Comment by wglambert** [comment]
https://github.com/docker-library/mysql/issues/422#issuecomment-386967535
The error message is directly from the OS, not something we can change in the image

https://github.com/docker-library/mysql/issues/303#issuecomment-327126327
You would want to configure Docker's seccomp profile

**Comment by AceHack** [comment]
I'm running in kubernetes

**Comment by tianon** [comment]
https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccomp

**Comment by AceHack** [comment]
We are not allowed to run elevated containers in our cluster.

**Comment by wglambert** [comment]
So in the pod security policy put [`privileged: false`](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#create-a-policy-and-a-pod)

Going to close since this isn't an issue we can alleviate in the image.
If you have further questions you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=kubernetes).

**Comment by greatyao** [comment]
how to fix?
