### ISSUE TITLE
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

### ISSUE THREAD

**Issue by Hye1Kim** [docker-library/cassandra#258]
Hello
If you run the casandra container, it does not run with the log as shown below. What should I change?

![image](https://user-images.githubusercontent.com/102787163/204987814-691bf23f-2488-427a-9019-e14d8b0ba3a3.png)
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

**Comment by tianon** [comment]
That looks like just a warning, and the actual failure is probably something deeper.  On that option specifically, that flag isn't something we've added, but something coming from Cassandra's own scripts, so is something that would need to be fixed upstream (but again, I really doubt that warning is the actual root cause of your failure to start Cassandra).

What I would suggest would be posting to a dedicated support forum, such as [the Docker Community Slack](https://dockr.ly/comm-slack), [Server Fault](https://serverfault.com/help/on-topic), [Unix & Linux](https://unix.stackexchange.com/help/on-topic), or [Stack Overflow](https://stackoverflow.com/help/on-topic).
