### ISSUE TITLE
Initialization script 

### ISSUE THREAD

**Issue by AnderUstarroz** [docker-library/cassandra#31]
This is a feature request,  
Some docker images like the [official postgres](https://hub.docker.com/_/postgres/) allow [initialization scrips](https://hub.docker.com/_/postgres/#how-to-extend-this-image) during execution. Just adding  some SQL or Shell files  to the folder **/docker-entrypoint-initdb.d** and docker will execute all these scripts after building the image, so we are able to create schemes, add initial data ETC... I believe this is a great feature and wouldn't be really hard to add to cassandra, just take a look at [postgres entry-point.sh ](https://github.com/docker-library/postgres/blob/ed23320582f4ec5b0e5e35c99d98966dacbc6ed8/9.4/docker-entrypoint.sh).

**Comment by yosifkit** [comment]
This one feels a bit more complicated than Mysql/Postgres.  The other images start the sql server with a limited listening state, ie only localhost or unix domain socket, in order to complete sql imports and scripts before stopping the server and starting it again as pid 1 with normal network access.  It would be a fairly major change to the current script to prepare the server with `localhost` listen and broadcast addresses, and to only do so if this is the first server, ie no `CASSANDRA_SEEDS`.

If this is something that is commonly wanted, I would not be opposed to a PR.

**Comment by tianon** [comment]
There are a couple workarounds discussed over in https://github.com/docker-library/cassandra/issues/65 if you have an oversimplified deployment.

**Comment by tianon** [comment]
Closing with a similar rationale to https://github.com/docker-library/cassandra/issues/94 -- the proper deployment of Cassandra is clustered, and is _much_ more complicated to get right automatically.  It is not recommended to use a standalone deployment, and I fear such a feature would encourage folks to do so (since it couldn't possibly work with a cluster properly and/or detect clustered operation).  For folks that really want to go there, building something like that on top of the provided image shouldn't be too much work. :+1:
