### ISSUE TITLE
opscenter

### ISSUE THREAD

**Issue by JMDierkes** [docker-library/cassandra#37]
Hi, I was wondering if you could help me figure out how to set up the datastax opscenter with this cassandra image on multiple ec2 instances. Thanks.

**Comment by yosifkit** [comment]
Normally it should be basically the same as if you were setting them on the machines without docker :smile:.  Just set the appropriate env vars for `CASSANDRA_BROADCAST_ADDRESS`, `CASSANDRA_RPC_ADDRESS`, and others that you may need so that they can talk from one machine to another (the docs have a simple example of this).  Also be sure to forward any ports you need to the host with `-p` and be sure to set the amazon security group settings appropriately to restrict communication on those ports :wink:.

I am not sure what access the opscenter agents need, I was assuming that a second container with it running would work, but I am not that familiar with it.

**Comment by tianon** [comment]
Given that this isn't an issue with the Cassandra image perse, I'm going to close this stale issue. Thanks! :+1:
