### ISSUE TITLE
Passing "CASSANDRA_RACK" and "CASSANDRA_DC" do nothing

### ISSUE THREAD

**Issue by antimack** [docker-library/cassandra#57]
Hi.
 I've started up 3 nodes Cassandra 2.1.13 cluster with passing some env variables like:
CASSANDRA_CLUSTER_NAME=mycluster
CASSANDRA_DC=dc2
CASSANDRA_RACK=rack2

but when I'm using "nodetool status" on a first node(seed node in my case) I see default "datacenter1" and "rack1" so it seems that passing this variables don't do nothing

```
root@39559689ed20:/# cat /etc/cassandra/cassandra-rackdc.properties | egrep -v "^\s*(#|$)"
dc= dc2
rack= rack2
```

```
root@39559689ed20:/# nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens  Owns (effective)  Host ID                               Rack
UN  192.168.0.4  107.39 KB  256     69.0%             6c39fcc4-a54d-407a-811f-f4bc3d5587b7  rack1
UN  192.168.0.3  120.16 KB  256     67.2%             f04417e4-0124-4eb4-842a-37636a14ab0d  rack1
UN  192.168.0.2  112.63 KB  256     63.8%             65ad3bdb-519e-4568-8370-8f53d0a0fd49  rack1
```

**Comment by muehan** [comment]
same here. created container
`docker run --name=n1 -d cassandra -CASSANDRA_DC=DC1 -CASSANDRA_RACK=RAC1`
 but status says
```
*******:~ # docker exec -it n1 nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  172.18.0.2  97.61 KB   256          ?       f7ee318d-2c00-44f1-9172-811962f8987e  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

**Comment by yosifkit** [comment]
We've had this since #6.  Dang :cry:.  Is there something we need to do to get cassandra to use the `cassandra-rackdc.properties`?

**Comment by tianon** [comment]
I think the discussion in https://github.com/docker-library/cassandra/pull/39#issuecomment-169093871 is relevant here, since it looks like setting `endpoint_snitch` requires additional configuration depending on which `snitch` you choose, so I'm more +1 to reverting this functionality and adding more documentation.  (since we'll need more documentation as-is already, since you have to set the `endpoint_snitch` as well)

**Comment by yosifkit** [comment]
You do need to set the snitch. This works to get the file used:
```console
$ docker run -d \
    -e CASSANDRA_CLUSTER_NAME=mycluster \
    -e CASSANDRA_DC=dc2 \
    -e CASSANDRA_RACK=rack2 \
    -e CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch \
    --name cass cassandra
```

Not sure about reverting :confused:, but I am leaning -1 on it.  I don't like removing functionality.

As for the other snitches needing more config values, it doesn't seem like we do:
- `SimpleSnitch`, default value, just works
- `RackInferringSnitch`, uses ip to determine rack and dc, probably not used in practice
  - "Use this snitch as an example of writing a custom Snitch class." -from the [docs](https://docs.datastax.com/en/cassandra/1.2/cassandra/architecture/architectureSnitchRackInf_c.html)
- `PropertyFileSnitch` needs a complete network map of your cassandra servers, which requires a whole file that would need to be added to the image (custom, not something we could conceivably generate)
- `GossipingPropertyFileSnitch`, the one that uses our `CASSANDRA_DC` and `CASSANDRA_RACK` generated file
- `Ec2Snitch`, uses amazon private ips, may work with `--net=host` or possibly `-e CASSANDRA_BROADCAST_ADDRESS="private aws ip" -p ...`
- `EC2MultiRegionSnitch`, uses public and private amazon ip address, so `BROADCAST_ADDRESS` and friends should work
  - will probably only work with `--net=host` since it needs access to the public and private IP of the host

(This is just from reading the documentation, I have not tested these.)

**Comment by j-potts** [comment]
@yosifkit what doc did you pull that from? I ran into this same issue, but found that SimpleSnitch does "recognize" dc or rack info per the Datastax Cassandra doc: https://docs.datastax.com/en/cassandra/2.1/cassandra/architecture/architectureSnitchSimple_c.html

I tested this using `docker-compose` with `CASSANDRA_ENDPOINT_SNITCH: "SimpleSnitch"` set, it did not add my Cassandra nodes to the datacenter specified with `CASSANDRA_DC`. However, if I change the endpoint to `CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"` it works.

If anything, it seems like updating the doc for `CASSANDRA_DC` to mention that the default `SimpleSnitch` will not honor this setting and pointing to the relevant Datastax doc would be worth the effort.

**Comment by markglh** [comment]
This seems like correct behaviour to me, it's just a change to the documentation that's required to make it clear how Cassandra works under these circumstances.

**Comment by j-potts** [comment]
@markglh 👍

**Comment by logronoide** [comment]
I'm trying to deploy a multi-datacenter cassandra 2.2.8 cluster with kubernetes, but I get this error:

```
Cannot start node if snitch's data center (MYDC) differs from previous data center ($(DC)). Please fix the snitch configuration, decommission and rebootstrap this node or use the flag -Dcassandra.ignore_dc=true.
```

The variables relevant in my k8s template are:
```
        env:
          - name: CASSANDRA_SEEDS
            value: "cassandra-0.cassandra,cassandra-1.cassandra,cassandra-2.cassandra"
          - name: PEER_DISCOVERY_SERVICE
            value: "cassandra-0.cassandra,cassandra-1.cassandra,cassandra-2.cassandra"
          - name: CASSANDRA_ENDPOINT_SNITCH
            value: GossipingPropertyFileSnitch
          - name: CASSANDRA_CLUSTER_NAME
            value: "Kong"
          - name: CASSANDRA_DC
            value: "MYDC"
          - name: CASSANDRA_RACK
            value: "Kong-Rack1"
```

It seems that the variables are passed to Cassandra, but the cassandra-rack.properties file is not updated. 

Reading the comments, I'm not sure if it's still an issue or there is a fix or workaround I can apply. 

Any thoughts? Thanks!
