### ISSUE TITLE
calculate_heap_sizes() on a Docker container

### ISSUE THREAD

**Issue by raimonbosch** [docker-library/cassandra#60]
Hi,

I checked that the function that calculates heap size uses the method "free -m" https://github.com/apache/cassandra/blob/trunk/conf/cassandra-env.sh which means that in a Docker container is going to consider always the OS system memory instead of the memory assigned to the container.

Is there a solution to this problem?

Thanks in advance,

**Comment by raimonbosch** [comment]
Replacing this:

```
Linux)
            system_memory_in_mb=`free -m | awk '/:/ {print $2;exit}'`
            system_cpu_cores=`egrep -c 'processor([[:space:]]+):.*' /proc/cpuinfo`
        ;;
```

by

```
Linux)
            system_memory_in_mb=`cat /sys/fs/cgroup/memory/memory.limit_in_bytes | awk '{print $1 / 1000000}'`
            system_cpu_cores=`cat /sys/fs/cgroup/cpu/cpu.shares | awk '{print $1 / 1024}'`
        ;;
```

would work on my set up.

**Comment by yosifkit** [comment]
Yeah, they really should be looking at `/proc/meminfo` rather than `free -m`, and this should be the minimum of the two, the `MemTotal` from `meminfo` and the cgroup limit, since the default value in the cgroup is `MAX_INT64 - 4095` and one can give memory limit values that are larger than actual RAM.

I am on the fence whether or not we should patch the given `cassandra-env.sh` to work correctly within cgoup limits.  It technically could apply to situations outside of docker, so it might be worth filing a bug upstream.

**Comment by raimonbosch** [comment]
Another solution could be to add this two lines on the Dockerfile:

#Adapt memory heap calculation to docker container:
RUN sed -i "s,system_memory_in_mb=\`free \-m.*,system_memory_in_mb=\`cat /sys/fs/cgroup/memory/memory.limit_in_bytes | awk \'{print int(\$1 / 1000000)}\'\`,g" /etc/cassandra/cassandra-env.sh
RUN sed -i "s,system_cpu_cores=\`egrep \-c .*,system_cpu_cores=\`cat /sys/fs/cgroup/cpu/cpu.shares | awk \'{print \$1 / 1024}\'\`,g" /etc/cassandra/cassandra-env.sh

That worked for me.

**Comment by yosifkit** [comment]
I would be hesitant to use just `cpu.shares` since it is an arbitrary weight relative to all other processes on the system and we don't know how many other processes are on the system and what their wrights are.  I think it would be complex combination of `/sys/fs/cgroup/cpu/cpu.cfs_quota_us`, `/sys/fs/cgroup/cpu/cpu.cfs_period_us`, `/sys/fs/cgroup/cpuset/cpuset.cpus`, and  `/sys/fs/cgroup/cpu/cpu.shares`.

Also, the memory limit would need to take more than just `memory.limit_in_bytes` since that can be huge when no limit is defined.

If you found a solution that works for you, that is great! :tada:  Unfortunately, I'm not sure I see a way to generalize this to work for everyone.

**Comment by luberg** [comment]
I tried adding @raimonbosch solution to my docker file and then every time I run nodetool I get this:  

root@ip-x-x-x-x:/# nodetool help
/usr/bin/nodetool: 47: [: Illegal number: 0.0996094
expr: non-integer argument
/usr/bin/nodetool: 81: [: Illegal number:

Any ideas?

**Comment by luberg** [comment]
When I use this

`RUN sed -i "s,system_memory_in_mb=\`free \-m.*,system_memory_in_mb=\`cat /sys/fs/cgroup/memory/memory.limit_in_bytes | awk \'{printf (\"%.0f\"\, \$1 / 1000000)}\'\`,g" /etc/cassandra/cassandra-env.sh`

it doesn't throw those strange errors and appears to be passing in the correct values.

**Comment by yosifkit** [comment]
You can use cassandra's built-in environment variables to configure memory usage:  `MAX_HEAP_SIZE` and `HEAP_NEWSIZE`.

See also https://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsTuneJVM.html

Still not wanting to patch upstream's `cassandra-env.sh` for cpu calculations.

**Comment by raimonbosch** [comment]
Hi @luberg,

Probably some of the separators got lost from the original sed through editing, but the important idea is to use the data corresponding to cgroup instead of baremetal values.

A cleaner solution is to use MAX_HEAP_SIZE and HEAP_NEWSIZE as @yosifkit pointed out.

Cheers,
