### ISSUE TITLE
Enhancement(UDF): environment variable

### ISSUE THREAD

**Issue by PAFsec** [docker-library/cassandra#92]
Hello,
It would be interesting to have the possibility of setting **enable_user_defined_functions=true** in our _cassandra.yaml_ through an environment variable like CASSANDRA_UDF_ENABLE=true.

Thank you so much for your work

**Comment by tianon** [comment]
I'm sorry, but honestly if we're going to do anything more with environment variables it would likely be in the opposite direction (which we won't do due to the backwards compatibility implications) -- modifying a YAML file via shell script is very fragile, and setting complex configuration in this way is not great.  For custom configuration, the only/best recommendation is to provide an appropriate `cassandra.yaml` file to your running instance (via a new image with `FROM` / `COPY` in a short `Dockerfile`, via [Docker Configs](https://docs.docker.com/engine/swarm/configs/), via bind mount, etc).

Closing in favor of https://github.com/docker-library/cassandra/pull/160 + https://github.com/docker-library/docs/pull/1317.
